### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by scottnath** [bjornicus/tddcss#1]
Node 0.12.0
OSX 10.10.2

Followed basic instructions and did nothing else. When I run `node ./startKarma.cmd`, I get this error:

```
/Users/.../development/testing/tddcss/startKarma.cmd:1
(function (exports, require, module, __filename, __dirname) { node node_module
                                                                   ^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

note, in my console the `^^^^^^^^^^^` section is referring to `node_module` in the line above it.

thanks for any help,
Scott

**Comment by bjornicus** [comment]
Hmm,  I just ran through the three steps on a new machine that I've not done this before on and didn't have a problem, but I'm on Windows.

Maybe try taking the .cmd script out of the equation and just run try running the karma server directly:
node node_modules\karma\bin\karma start

**Comment by scottnath** [comment]
Tried again, this time with forward slashes:

```
node node_modules/karma/bin/karma start
```

started right up. Are backward slashes for windows machines?

**Comment by bjornicus** [comment]
yes, paths on Windows use back slashes, Linux and OSX use front slashes.  But I just realized that since the path is being passed to node it might work with front slash on windows too (because node would be smart enough to find the script anyway).  I tried it and it did, so I'll try to change it if I get a chance.

**Comment by scottnath** [comment]
Cool. thanks.
